### ISSUE TITLE
'str' object has no attribute 'columns'

### ISSUE THREAD

**Issue by huangzhenhao90** [zmcddn/Data-Science-Helper#1]
Traceback (most recent call last):
  File "ds.py", line 2, in <module>
    dshelper.dshelp('/users/xx/xx/xx.txt')
  File "/anaconda3/lib/python3.6/site-packages/dshelper/dshelper.py", line 455, in dshelp
    frame = MainFrame(df, app)
  File "/anaconda3/lib/python3.6/site-packages/dshelper/dshelper.py", line 361, in __init__
    self.df = prepare_df(df)
  File "/anaconda3/lib/python3.6/site-packages/dshelper/dshelper.py", line 435, in prepare_df
    columns = list(df.columns.values)
AttributeError: 'str' object has no attribute 'columns'

**Comment by huangzhenhao90** [comment]
> @huangzhenhao90 What kind of df were you using? Can you provide a sample of it?

![image](https://user-images.githubusercontent.com/33592619/51537013-4eec3800-1e88-11e9-91c3-cc885b682ea6.png)

**Comment by huangzhenhao90** [comment]
> @huangzhenhao90 What kind of df were you using? Can you provide a sample of it?

![image](https://user-images.githubusercontent.com/33592619/51537057-6cb99d00-1e88-11e9-85a8-0942f5810c42.png)

**Comment by zmcddn** [comment]
@huangzhenhao90 

I tried with the following code to produce your sample and it worked.

    import dshelper 
    import pandas as pd
    num = list(range(9,21))
    val = [158900, 16470, 109005, 101430, 170310, 170475,
        180025, 180290, 180385, 190410, 200830, 20090
        ]
    df = pd.DataFrame(val, index=num)
    dshelper.dshelp(df)

You have to make sure you are passing pandas dataframe into the GUI.
Let me know if you have further questions
