### ISSUE TITLE
dshelper issue report

### ISSUE THREAD

**Issue by frank-yifei-wang** [zmcddn/Data-Science-Helper#2]
Hi I tried dshelper and found these issues (see screenshot):

1. **wx.lib.pubsub deprecated** - to migrate to pypubsub
2. **The kernel kept running** without generating the result. Had to interrupt the kernel in the end

Please look into this. Thanks.

![dshelper-issue](https://user-images.githubusercontent.com/42301547/63877857-a2c28080-c985-11e9-8b38-7c938f269cd9.png)

**Comment by frank-wang-yifei** [comment]
Just to let you know I submitted [a gist](https://gist.github.com/frank-wang-yifei/b627019cd73b768b0dd82624f5260d5b) based on a DataFrame viewing code snippet I wrote. I'd encourage you to continue to develop dshelper with a similar front end.
